environment:
  matrix:
    - APPVEYOR_RUST_CHANNEL: stable
    - APPVEYOR_RUST_CHANNEL: nightly

install:
  # Install rust, x86_64-pc-windows-msvc host
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host x86_64-pc-windows-msvc --default-toolchain %APPVEYOR_RUST_CHANNEL%
  - set PATH=C:\msys64\usr\bin;%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

for:
  - matrix:
      only:
        - APPVEYOR_RUST_CHANNEL: stable
    test_script:
      - cd %APPVEYOR_BUILD_FOLDER%\serde
      - cargo build --features rc
      - cargo build --no-default-features
      - cd %APPVEYOR_BUILD_FOLDER%\serde_test
      - cargo build
      - cargo test --features serde/derive,serde/rc

  - matrix:
      only:
        - APPVEYOR_RUST_CHANNEL: nightly
    test_script:
      - cd %APPVEYOR_BUILD_FOLDER%\serde
      - cargo build
      - cargo build --no-default-features
      - cargo build --no-default-features --features alloc
      - cargo build --no-default-features --features rc,alloc
      - cargo test --features derive,rc,unstable
      - cd %APPVEYOR_BUILD_FOLDER%\test_suite
      - cargo test --features unstable
